# Generated by Django 2.2.3 on 2019-07-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelex', '0002_auto_20190710_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.CharField(choices=[('draft', 'Draft'), ('publish', 'Publish'), ('private', 'Private')], default='draft', max_length=120),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, null=True, verbose_name='Post Title'),
        ),
    ]
