# Generated by Django 2.2.3 on 2019-07-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelex', '0004_auto_20190710_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120, null=True, unique=True, verbose_name='Post Title'),
        ),
    ]
