# Generated by Django 2.2.3 on 2019-07-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelex', '0006_auto_20190710_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
