# Generated by Django 2.2.3 on 2019-07-10 13:09

from django.db import migrations, models
import modelex.models


class Migration(migrations.Migration):

    dependencies = [
        ('modelex', '0007_post_author_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author_email',
            field=models.CharField(blank=True, max_length=220, null=True, validators=[modelex.models.validate_author_email]),
        ),
    ]
